// - Create the skeleton for 4 routes
//     - POST /signup
//     - POST /login
//     - POST /todo (authenticated)
//     - GET /todos (authenticated)
const express=require('express');
const app=express();
app.use(express.json());//middleware to parse json body

const cors=require('cors');
app.use(cors());

const jwt=require('jsonwebtoken');
const jwtsecret="Shubh";

//import the data coming from database
const mongoose=require('mongoose');
const {UserModel,TodoModel}=require("./db");
mongoose.connect("mongodb+srv://jainsnehal9946_db_user:kvMxd5ZmPMU9fbxI@cluster0.ororj5j.mongodb.net/to-do-app-database");

app.post("/signup",async function(req,res){
    const username=req.body.username;
    const password=req.body.password;
    const age=req.body.age;
    await UserModel.create({//means to insert
        username:username,
        password:password,
        age:age

    });
    res.json({
        message:"Signup successfully"
    })


});
app.post("/login",async function(req,res){
    const username=req.body.username;
    const password=req.body.password;
    
    const usercame=await UserModel.findOne({
        username:username,
        password:password
    });
    // console.log(usercame);

    if(usercame)
    {
        //if the user exists then generate them a jwt token with the _id thingy
        // this random ahh long thingy is generated by MongoDB and thus will be used to uniquely identify the user
        const token=jwt.sign({
            id:usercame._id.toString()//this is actually called payload means what data you are storing

        },jwtsecret);
        res.json({
            token:token,
            message:"Login successful"

        });

    }else{
        res.status(403).json({
            message:"Invalid credemtials"
        })

    }

});

//both of these api  need to be authenticated
//THIS IS BASICALLY THE AUTHENTICATION MIDDLEWARE FOR JWT
function auth(req,res,next)
{
    //fetch the token coming after loggin in
    const token=req.headers.token;//get the token back,from the /login endpoint
    const decodedData=jwt.verify(token,jwtsecret);

    //now check that the deocded data exists in db or not
    //now data can be faked but id cannot be
    if(decodedData)//means if the decoded data matches with the data present in database
    {
        req.userID=token.userID;
        next();//call the next lineage function
    }else{
        res.status(403).json({
            message:"Invalid credentials"
        })
    }
}

app.post("/todosput",auth, async function(req,res){
    //since this end point can only be reached after authentication
    //means the user here is alr authenticated
    const task=req.body.task;
    const status=req.body.status;
    const userID=req.userID;

    await TodoModel.create({//means to insert
        task:task,
        status:status,
        userID:userID

    });
    res.json({
        message:"Todo created"
    })



});
//this end point will give the list of the todos,for the logged in ID
app.get("/todosget",auth,async function(req,res){
    const userID=req.userID;

    const todos=await TodoModel.find({
        userID
    });

    res.json({
        todos
    });


});


app.listen(3000);
