// - Create the skeleton for 4 routes
//     - POST /signup
//     - POST /login
//     - POST /todo (authenticated)
//     - GET /todos (authenticated)
const express=require('express');
const app=express();

const cors=require('cors');
app.use(cors());

//import the data coming from database
const mongoose=require('mongoose');
const {UserModel,TodoModel}=require("./db");

const jwt=require('jsonwebtoken');
const jwtsecret="Shubh";

app.use(express.json());//middleware to parse json body
mongoose.connect("mongodb+srv://jainsnehal9946_db_user:kvMxd5ZmPMU9fbxI@cluster0.ororj5j.mongodb.net/to-do-app-database");

app.post("/signup",async function(req,res){
    const username=req.body.username;
    const password=req.body.password;
    const age=req.body.age;
    await UserModel.create({//means to insert
        username:username,
        password:password,
        age:age

    });
    res.json({
        message:"Signup successfully"
    })


});
app.post("/login",async function(req,res){
    const username=req.body.username;
    const password=req.body.password;
    
    const usercame=await UserModel.findOne({
        username:username,
        password:password
    });
    // console.log(usercame);

    if(usercame)
    {
        //if the user exists then generate them a jwt token with the _id thingy
        // this random ahh long thingy is generated by MongoDB and thus will be used to uniquely identify the user
        const token=jwt.sign({
            id:usercame._id.toString()

        },jwtsecret);
        res.json({
            token:token,
            message:"Login successful"

        });

    }else{
        res.status(403).json({
            message:"Invalid credemtials"
        })

    }

});

//both of these api  need to be authenticated
function auth(req,res,next)
{
    //fetch the token coming after loggin in
    const token=req.header.token;
    const decodedData=jwt.verify(token,jwtsecret);

    //now check that the deocded data exists in db or not
    //now data can be faked but id cannot be
    if(decodedData)
    {
        req.userID=decodedData.userID;
        next();//call the next lineage function
    }else{
        res.status(403).json({
            message:"Invalid credentials"
        })
    }
}

app.post("/todoput",auth,function(req,res){


});
app.get("/todosget",auth,function(req,res){

});


app.listen(3000);
