// - Create the skeleton for 4 routes
//     - POST /signup
//     - POST /login
//     - POST /todo (authenticated)
//     - GET /todos (authenticated)
const express=require('express');
const app=express();
app.use(express.json());//middleware to parse json body

const cors=require('cors');
app.use(cors());

const jwt=require('jsonwebtoken');
const jwtsecret="Shubh";

//import the data coming from database
const mongoose=require('mongoose');
const {UserModel,TodoModel}=require("./db");
mongoose.connect("connection-url-username-password/to-do-app-database");

const bcrypt=require("bcrypt");
const {z}=require("zod");
//zod librarary is basically used for input validations


app.post("/signup",async function(req,res){
    //before fetching anything you first had to SET AND VALIDATE THE SCHEMA of the incoming data
    //LIKE YOU NEED TO RESTRICT USER FOR WHAT THEY CAN SEND
    const requiredBody=z.object({
        username:z.string().min(3).max(100).email(),
        password:z.string().min(4).max(100),
        age:z.number().positive().minValue(10).maxValue(100)

    });
    //AFTER YOU HAVE STRICTLY DEFINED THE VALIDATIONS FOR YOUR INPUT YOU CAN DO WHATEVER YOU WANT


    const username=req.body.username;
    const password=req.body.password;
    const age=req.body.age;

    //AFTER FETCHING THE DATA YOU MUST CHECK WEATHER IT IS VALIDATED OR NOT
    //so you now basically parse the incoming req.body
    const parsedDatawithSuccess=requiredBody.safeParse(req.body);

    if(!parsedDatawithSuccess.success)////means after parsing the data recieved from req.body does not matches with the strict schema validation we made by zod
    {
        res.json({
            message:"Incorrect format",
            error:parsedDatawithSuccess.error//this function lets user know what actually is
            //wrong with their entered data
        });
        return;

    }
    


    try{
        const hashedpassword=await bcrypt.hash(password,5);//this 5 basically means ki aap kitne salt rounds karoge
    //we awaited because its a async function yk dont know how many salt rounds you do
    //the more the value the more it will be computationally expensive to brute force
    await UserModel.create({//means to insert
        username:username,
        password:hashedpassword,
        age:age
        
        //now this usermodel will throw error if multiple user exists

    });
    res.json({
        message:"Signup successfully"
    });

}catch(e)
    {
        res.json({
            message:"User already exists"
        })

    }

    


});
app.post("/login",async function(req,res){
    const username=req.body.username;
    const password=req.body.password;
    
    const usercame=await UserModel.findOne({
        username:username,
        // password:password
    });
    // console.log(usercame);
    if(!usercame)
    {
        res.json({
            message:"User does not exists"
        });
    }else{
        try{
            const matchedpassw=await bcrypt.compare(password,usercame.password);//
    //this bcrypt function directly compares the hashed password stored in db 
    //and the password that just fetched when the user was siging in,to autheticate

    if(matchedpassw)//means the password is correct
    {
        //if the user exists then generate them a jwt token with the _id thingy
        // this random ahh long thingy is generated by MongoDB and thus will be used to uniquely identify the user
        const token=jwt.sign({
            id:usercame.id.toString()//this is actually called payload means what data you are storing

        },jwtsecret);

        res.json({
            token:token,
            message:"Login successful"

        });

    }else{
        res.status(403).json({
            message:"Invalid credemtials"
        })

    }
        }catch(e)
        {
            res.json({
                message:e
            });
        }
    

    
}

});


//both of these api  need to be authenticated
//THIS IS BASICALLY THE AUTHENTICATION MIDDLEWARE FOR JWT
function auth(req,res,next)
{
    //fetch the token coming after loggin in
    const token=req.headers.token;//get the token back,from the /login endpoint
    if(!token)
    {
        res.json({
            message:"No token provided"
        })
    }
   try{
     const decodedData=jwt.verify(token,jwtsecret);

    //now check that the deocded data exists in db or not
    //now data can be faked but id cannot be
    if(decodedData)//means if the decoded data matches with the data present in database
    {
        req.userID=decodedData.id;
        next();//call the next lineage function
    }else{
        res.status(403).json({
            message:"Invalid credentials"
        })
    }
   }catch(e)
   {
    res.json({
        message:"Token expired"
    })
   }
}

app.post("/todosput",auth, async function(req,res){
    //since this end point can only be reached after authentication
    //means the user here is alr authenticated
    const task=req.body.task;
    const status=req.body.status;
    const userID=req.userID;

    await TodoModel.create({//means to insert
        task:task,
        status:status,
        userID:userID

    });
    res.json({
        message:"Todo created"
    })



});
//this end point will give the list of the todos,for the logged in ID
app.get("/todosget",auth,async function(req,res){
    const userID=req.userID;

    const todos=await TodoModel.find({
        userID
    });

    res.json({
        todos
    });


});


app.listen(3000);
